In [2]:
!pip install datasets evaluate

!pip install "transformers==4.40.0"

Collecting datasets
  Downloading datasets-2.19.0-py3-none-any.whl (542 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 3.6 MB/s eta 0:00:00
Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.5 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.13.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.25.2)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (14.0.2)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 13.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 16.6 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.2 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2024.3.1,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Collecting huggingface-hub>=0.21.2 (from datasets)
  Downloading huggingface_hub-0.22.2-py3-none-any.whl (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 30.4 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, dill, responses, multiprocess, huggingface-hub, datasets, evaluate
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
Successfully installed datasets-2.19.0 dill-0.3.8 evaluate-0.4.1 huggingface-hub-0.22.2 multiprocess-0.70.16 responses-0.18.0 xxhash-3.4.1
Requirement already satisfied: transformers==4.40.0 in /usr/local/lib/python3.10/dist-packages (4.40.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (3.13.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (0.22.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (2023.12.25)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.40.0) (4.66.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.40.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.40.0) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.40.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.40.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.40.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.40.0) (2024.2.2)

In [ ]:
!pip install transformers[torch]
!pip install accelerate -U

In [ ]:
from huggingface_hub import login
login(token='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', add_to_git_credential=True)

In [5]:
import pandas as pd
import numpy as np
import os
import evaluate
import librosa
from datasets import load_dataset, Audio, load_metric, Dataset, load_from_disk, DatasetDict

In [ ]:
def get_files(path):
    data_ = []
    count = {}
    files = os.listdir(path)
    for file in files:

        parts = file.split("-")
        if len(parts) >= 4:
            stress_and_date = parts[2]
            stress = stress_and_date.split("_")[0]
            filepath = os.path.join(path, file)

            audio, sample_rate = librosa.load(filepath, sr=None)  # Load audio without resampling
            data = {
                "stress": stress,
                "path": filepath,
                "audio": audio,
                "sample_rate": sample_rate
            }

            for label in [stress]:
                count[label] = count.get(label, 0) + 1
            data_.append(data)
    if data_:
        df = pd.DataFrame(data_)
    else:
        df = pd.DataFrame(columns=['stress', 'path', 'audio', 'sample_rate'])
    return data_, count, df

path = '/content/drive/MyDrive/EmoAug'
dataset, count, df = get_files(path)
df_nopath = df.iloc[:, :-1]

print(count)
print()
print(df.head())
print("Total Number of samples: ", len(df))

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['stress'] = le.fit_transform(df['stress'])

label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Label mapping:", label_mapping)

print(df)

In [ ]:
# df.to_csv('/content/drive/MyDrive/EmoGram/augmented_data.csv',index=None)

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/EmoGram/augmented_data.csv")

In [ ]:
def convert_dataset(data):
    new_dataset = []
    for _, row in data.iterrows():
        new_data = {}
        # Load the audio file and get its array and sampling rate
        audio_path = row['path']
        audio, sampling_rate = librosa.load(audio_path, sr=None)
        # Create the new 'audio' dictionary
        new_data['audio'] = {
            'array': audio,
            'path': audio_path,
            'sampling_rate': sampling_rate
        }
        # Add 'stress' value to the new data
        new_data['stress'] = row['stress']
        # Append the new data to the new dataset
        new_dataset.append(new_data)
    return new_dataset


data_ac = convert_dataset(data)

In [ ]:
print(len(data_ac[0]['audio']['array']))

48000

In [ ]:
print(data_ac[0])

{'audio': {'array': array([ 0.00210571,  0.00234985,  0.00228882, ..., -0.00054932,
       -0.0007019 , -0.0007019 ], dtype=float32), 'path': '/content/drive/MyDrive/EmoAug/help-safe-calm-20190727194556-d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42fpitchshift2.0.wav', 'sampling_rate': 16000}, 'stress': 2}

Saving as list

In [ ]:
import pickle
from datasets import Dataset

# with open("data_ac.pkl", "wb") as f:
#     pickle.dump(data_ac, f)

In [ ]:
with open("/content/drive/MyDrive/EmoGram/data_ac.pkl", "rb") as f:
    data_ac = pickle.load(f)

In [ ]:
audio_dataset = Dataset.from_list(data_ac)

In [ ]:
audio_dataset[0]

In [ ]:
audio_dataset.save_to_disk("/content/drive/MyDrive/EmoGram/fifteen_data")

In [ ]:
# audio_dataset.to_json("/content/drive/MyDrive/EmoGram/properfjson_data.json")

Space

In [ ]:
minds=load_from_disk("/content/drive/MyDrive/EmoGram/fifteen_data")

In [ ]:
minds

In [ ]:
minds.features

In [ ]:
# 70-train | 10-validation | 20-test
minds_tvt = minds.train_test_split(test_size=0.3)

In [ ]:
minds_tvt

In [ ]:
minds_valt = minds_tvt['test'].train_test_split(test_size=0.6)

In [ ]:
minds_valt

In [ ]:
train_test_valid_dataset = DatasetDict({
    'train': minds_tvt['train'],
    'test': minds_valt['test'],
    'valid': minds_valt['train']})

## Now our dataset is in proper format

In [10]:
train_test_valid_dataset = load_from_disk("/content/drive/MyDrive/data_split")

In [11]:
safety_data = train_test_valid_dataset

In [ ]:
# train_test_valid_dataset.save_to_disk("/content/drive/MyDrive/EmoGram/train_test_valid_dataset")

# Transformer Training

In [ ]:


# checkpoin_t = "aherzberg/ser_model_fixed_label"
# checkpoint = "ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition"

# # Load the tokenizer and model
# processor = AutoProcessor.from_pretrained(checkpoint)
# # tokenizer = AutoTokenizer.from_pretrained(checkpoint)
# model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

# # Define the evaluation metric
# metric = load_metric("glue", "mrpc")

# # Define the training arguments
# training_args = TrainingArguments(
#     output_dir="my_model_output",
#     num_train_epochs=5,
#     per_device_train_batch_size=16,
#     per_device_eval_batch_size=16,
#     weight_decay=0.01,
# )

# # Define the trainer
# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset= train_test_valid_dataset['train'],
#     eval_dataset= train_test_valid_dataset['valid'],
#     compute_metrics=metric,
#     tokenizer=processor,
# )

# # Train the model
# trainer.train()

# # Evaluate the model on the test set
# trainer.evaluate(train_test_valid_dataset['test'])

In [12]:
from transformers import AutoTokenizer, AutoModelForAudioClassification, AutoModelForSequenceClassification, TrainingArguments, Trainer, AutoProcessor, AutoFeatureExtractor

# from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2ForSpeechClassification

In [13]:
feature_extractor = AutoFeatureExtractor.from_pretrained("facebook/wav2vec2-base")

In [14]:
def preprocess_function(examples):
    audio_arrays = [x["array"] for x in examples["audio"]]
    inputs = feature_extractor(
        audio_arrays, sampling_rate=feature_extractor.sampling_rate, max_length=16000, truncation=True
    )
    return inputs

In [15]:
safety_data = safety_data.map(preprocess_function, remove_columns="audio", batched=True)
safety_data = safety_data.rename_column("stress", "label")

In [20]:
# verifying the proper format - features: ['input_values', 'label']
safety_data

DatasetDict({
    train: Dataset({
        features: ['label', 'input_values'],
        num_rows: 10888
    })
    test: Dataset({
        features: ['label', 'input_values'],
        num_rows: 2801
    })
    valid: Dataset({
        features: ['label', 'input_values'],
        num_rows: 1866
    })
})

In [17]:
len(safety_data['train'][0]['input_values']) # sample rate

16000

In [ ]:
# unique_labels = set()

# for record in safety_data['train']:
#     unique_labels.add(record['label'])

# print(unique_labels)

In [18]:
accuracy = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    predictions = np.argmax(eval_pred.predictions, axis=1)
    return accuracy.compute(predictions=predictions, references=eval_pred.label_ids)

Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]

In [ ]:
# num_labels = len(id2label)
model = AutoModelForAudioClassification.from_pretrained("facebook/wav2vec2-base", num_labels = 5)


# Define the training arguments
epochs = 30
training_args = TrainingArguments(
    output_dir="TransMod",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-5,
    gradient_accumulation_steps=4,
    num_train_epochs=epochs,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    warmup_ratio=0.1,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    push_to_hub=True,
)

# Define the trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=safety_data['train'],
    eval_dataset= safety_data['valid'],
    compute_metrics=compute_metrics,
    tokenizer=feature_extractor,
)

# Train the model
trainer.train()

pytorch_model.bin:   0%|          | 0.00/380M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at facebook/wav2vec2-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'projector.bias', 'projector.weight', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
trainer.evaluate()

# Finetuning a large trained SER with wav2vec base

In [ ]:
# ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition

# i think feature extraction would be same, check metric and other hyperparameters of the model before training

In [21]:
# num_labels = len(id2label)
model = AutoModelForAudioClassification.from_pretrained("ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition", num_labels = 5)


# Define the training arguments
epochs = 10
training_args = TrainingArguments(
    output_dir="TransMod",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-5,
    gradient_accumulation_steps=4,
    num_train_epochs=epochs,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    warmup_ratio=0.1,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    push_to_hub=True,
)

# Define the trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=safety_data['train'],
    eval_dataset= safety_data['valid'],
    compute_metrics=compute_metrics,
    tokenizer=feature_extractor,
)

# Train the model
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:363: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Some weights of the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition were not used when initializing Wav2Vec2ForSequenceClassification: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.output.bias', 'classifier.output.weight', 'wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForSequenceClassification were not initialized from the model checkpoint at ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition and are newly initialized: ['classifier.bias', 'classifier.weight', 'projector.bias', 'projector.weight', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

TrainOutput(global_step=1700, training_loss=0.625920151682461, metrics={'train_runtime': 7091.7582, 'train_samples_per_second': 15.353, 'train_steps_per_second': 0.24, 'total_flos': 3.29526634472064e+18, 'train_loss': 0.625920151682461, 'epoch': 9.985315712187958})

In [22]:
trainer.evaluate()

{'eval_loss': 0.5710384845733643,
 'eval_accuracy': 0.8129689174705252,
 'eval_runtime': 46.5224,
 'eval_samples_per_second': 40.11,
 'eval_steps_per_second': 2.515,
 'epoch': 9.985315712187958}